language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.9.0
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -r requirements.txt 
# before_script:
#   - "pep8 --exclude=migrations --ignore=E501,E225 src"
script: nosetests
