# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='song_limit',
            field=models.IntegerField(default=3),
        ),
    ]
