# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_room_song_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.PositiveIntegerField(max_length=12)),
                ('songs_added', models.PositiveIntegerField(max_length=3)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
    ]
